In [7]:
pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [11]:
array1 = np.array([12,3,4])#1D Array 
print(array1)
array1

[12  3  4]


array([12,  3,  4])

In [14]:
array2 = np.array([[12,3,4],[10,15,35],[1,19,80]]) #2D Array / Data
print(array2)
array2

[[12  3  4]
 [10 15 35]
 [ 1 19 80]]


array([[12,  3,  4],
       [10, 15, 35],
       [ 1, 19, 80]])

In [3]:
array3 = np.array([[[12,3,4],[10,15,35],[1,19,80]]]) #3D Array / Data
print(array3)
array3

[[[12  3  4]
  [10 15 35]
  [ 1 19 80]]]


array([[[12,  3,  4],
        [10, 15, 35],
        [ 1, 19, 80]]])